# Generated by Django 3.1.3 on 2021-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20201206_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('noteobook', models.ManyToManyField(related_name='tags', to='notebook.NoteBook')),
            ],
        ),
    ]
