# Generated by Django 3.1.3 on 2021-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='noteobook',
        ),
        migrations.AddField(
            model_name='notebook',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notebooks', to='notebook.Tag'),
        ),
    ]
